# Generated by Django 4.0.4 on 2022-05-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('views', models.IntegerField(blank=True, default=0)),
                ('clicks', models.IntegerField(blank=True, default=0)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Стастистики',
                'ordering': ['-date'],
            },
        ),
    ]
