# Generated by Django 4.0.4 on 2022-05-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistica', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statist',
            new_name='Info',
        ),
    ]
