# Generated by Django 4.0.4 on 2022-05-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistica', '0002_rename_statist_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Стастистики'},
        ),
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateField(),
        ),
    ]
